apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
data:
  MYSQL_HOST: {{ .Values.app.config.mysqlHost | quote }}
  MYSQL_DB: {{ .Values.app.config.mysqlDb | quote }}
  SESSION_REDIS_HOST: {{ .Values.app.config.sessionRedisHost | quote }}
  SESSION_REDIS_PORT: {{ .Values.app.config.sessionRedisPort | quote }}
