apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  MYSQL_USER: {{ .Values.app.secret.mysqlUser | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.app.secret.mysqlPassword | b64enc | quote }}
  SECRET_KEY: {{ .Values.app.secret.secretKey | b64enc | quote }}
